name: Build and Push MySQL Image

on:
  push:
    branches:
      - master

jobs:
  build_and_push_mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build MySQL Docker Image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ github.repository }}-mysql:latest .

    - name: Set up Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push MySQL Docker Image to GitHub Container Registry
      run: |
        docker tag ${{ github.repository }}-mysql:latest ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-mysql:latest
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-mysql:latest
